NomProduct = input('Dime le nombre del producto: ')
PreProduct = float(input('Dime el precio del producto: '))
UniProduct = input('Dime las unidades que vas a comprar: ')
Costetotal = float(PreProduct) * int(UniProduct)
print(NomProduct, round(PreProduct, 2), UniProduct ,round(Costetotal,2))
